### ISSUE TITLE
creating an alert with labelname and no matcher creates a 400 in the interface

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/alertmanager#1731]
![br](https://user-images.githubusercontent.com/291750/52065231-60af9880-2576-11e9-8736-eeac8be60469.png)

I often create alerts with random label name and no value, that silences everything in the AM.

But it generates a 400 http error in the interface.

**Comment by yeya24** [comment]
At this place the alertmanager tries to fetch the affected alerts.
Send a get request for the url below. The filter parameter is invalid here. I think we should not allow to create no value matchers
```
http://localhost:9093/api/v2/alerts?silenced=true&inhibited=false&filter=test=
```

**Comment by mxinden** [comment]
> I often create alerts with random label name and no value, that silences everything in the AM.

I am a bit confused here, do you mean "I often create **silences** with [...]"?

> But it generates a 400 http error in the interface.

In case you meant _silences_, API v2 required each matcher to have a value, see [Open API specification](https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml#L348). What would be the real world use case for creating a silence with a matcher without a name?

**Comment by roidelapluie** [comment]
@mxinden real world use case is silencing ALL the alerts.

**Comment by roidelapluie** [comment]
Or silencing alerts that do not have a certain label

**Comment by roidelapluie** [comment]
It is not without value, it is with an empty value.

**Comment by stuartnelson3** [comment]
>Or silencing alerts that do not have a certain label

This is a valid usecase, which we do want to support. I'm not sure that https://github.com/prometheus/alertmanager/pull/1789 is correct (I've asked a clarifying question there). I think what we want to do is fix the marshaling inconsistency between the alerts page and the silences form:

alerts page:
`/api/v2/alerts?silenced=false&inhibited=false&filter={master=""}`

silences form:
`/api/v2/alerts?silenced=true&inhibited=true&filter=master=`

A workaround right now is to put the matcher value as `""`.

So I suppose I see two problems:

1. The marshaling on the silences form should have the same result as the marshaling for the alerts page
2. An empty matcher value on the silences form should be marshaled as `""`, not just an empty string.

@roidelapluie does this sound ok?

**Comment by simonpasquier** [comment]
I've checked quickly and this is fixed by #1869. Feel free to re-open @roidelapluie if you don't agree ;-)

**Comment by twiedenbein** [comment]
#1869 does not seem to fix this issue.

Running latest HEAD:

`level=error ts=2019-05-14T18:42:23.624Z caller=api.go:218 component=api version=v2 msg="failed to parse matchers" err="bad matcher format: foo="`

**Comment by stuartnelson3** [comment]
What do the requests being made by the UI look like? I just built from 890d20555e5638c599f4af606953c0ea63d852ae and silence creation, silence preview, and viewing the silence were all successful:

Creation
```
curl 'http://localhost:9093/api/v2/silences' 
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0' 
-H 'Accept: */*' 
-H 'Accept-Language: en-US,en;q=0.5' --compressed 
-H 'Referer: http://localhost:9093/' 
-H 'Content-Type: application/json' 
-H 'Connection: keep-alive' 
--data '{"matchers":[{"name":"fdas","value":"","isRegex":false}],"startsAt":"2019-05-14T19:00:22.050Z","endsAt":"2019-05-14T21:00:22.050Z","createdBy":"stn","comment":"dsa","id":null}'
```
Silence preview
```
GET /api/v2/alerts?filter=fdas%3D%22%22&silenced=true&inhibited=true&active=true HTTP/1.1
Host: localhost:9093
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:9093/
Connection: keep-alive
```
Silence show (json response)
```
{
  "id": "51b16913-1e3f-4732-9a76-e5f4e224ee04",
  "status": {
    "state": "active"
  },
  "updatedAt": "2019-05-14T19:00:33.515Z",
  "comment": "dsa",
  "createdBy": "stn",
  "endsAt": "2019-05-14T21:00:22.050Z",
  "matchers": [
    {
      "isRegex": false,
      "name": "fdas",
      "value": ""
    }
  ],
  "startsAt": "2019-05-14T19:00:33.515Z"
}
```
