### ISSUE TITLE
-web.external-url does it work?

### ISSUE THREAD

**Issue by mokshpooja** [prometheus/alertmanager#323]
Hi Guys,

I am using proxy thus both prometheus and alert manager are both behind proxy. I used -web.external-url in prometheus which is working fine but this doesn't seem to be happening for alert manager.
I can reach the main page alert page but not the css or any other styling files thus i see a very primitively styled page.

**Comment by juliusv** [comment]
Hi, this should have gotten fixed in https://github.com/prometheus/alertmanager/pull/289, but the newest release doesn't contain that fix yet (0.1.1 is from March 15, the fix is from March 30).

/cc @fabxc for maybe doing a release already, but I know he's quite busy right now...

**Comment by juliusv** [comment]
Closing the issue here, since most likely this is fixed in master.

**Comment by mokshpooja** [comment]
buildng from master works. Thanks. Hope the release is out soon.

**Comment by fabxc** [comment]
@juliusv please see prometheus/prometheus#1191 and @chancez's suggestion.
`-web.external-url` currently doesn't solve all cases and should we change it, we shouldn't release it for AM in the first place.

**Comment by jcollie** [comment]
Just tried out 0.7.0-rc.0 and it's failing because the main page has an absolute reference to "/script.js".

**Comment by stuartnelson3** [comment]
The path is correct. I just downloaded and ran the release candidate, and experienced no failure.

**Comment by jcollie** [comment]
The path "/script.js" is only correct if you have AlertManager at the root of the URL path. If, like me, you are using a proxy in front of AlertManager to put it into a subdirectory it's not correct. I have the proxy set up so that https://www.example.com/prometheus forwards to my Prometheus installation and https://www.example.com/alertmanager forwards to my AlertManager installation.

**Comment by psalaberria002** [comment]
I can confirm this is also happening here with v0.7.0-rc.0

**Comment by stuartnelson3** [comment]
Ah, thanks for the clarification

**Comment by psalaberria002** [comment]
@mxinden I think this should be added to v0.7 Milestone. It should be an easy fix.

**Comment by mxinden** [comment]
@psalaberria002 @jcollie We have fixed this with #836. You can try out current master or wait a little. We are planning to release again hopefully tomorrow. Let me know if you are having any further issues with this.
