### ISSUE TITLE
Discord webhook : Cannot send an empty message

### ISSUE THREAD

**Issue by lazbord** [prometheus/alertmanager#3923]
**What did you do?**

I tried to triggered my discord webhook when an alert is firing.
I tested my discord webhook with curl and it work just fine : 

`curl -X POST -H "Content-Type: application/json" -d '{"content": "Another test!"}' https://discord.com/api/webhooks/discordwebhooktoken
`
![image](https://github.com/user-attachments/assets/6c316de4-731d-4f25-9632-fa85f068cd78)

Prometheus and Alermanager do recognize the alert : 

![image](https://github.com/user-attachments/assets/c89fc163-f40c-4768-b173-6076fea50eec)

![image](https://github.com/user-attachments/assets/8c9624f7-7019-44eb-b8f1-eccc49db4253)

Everything seemed to work but i don't have any messages in my discord channel when an alert is firing.

Here is the log from alertmanager : 

```
`Jul 19 12:54:37 CT-Monitoring alertmanager[3075]: ts=2024-07-19T12:54:37.265Z caller=dispatch.go:353 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="discord_webhook/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://discordapp.com/api/webhooks/mywebhooktoken: {\"message\": \"Cannot send an empty message\", \"code\": 50006}"`
```

I have tried to resolve this issue by specifying template that specifies a message but it doesn't change a thing. 

I'm a newbie so maybe I miss something out, but I believe I have done everything correctly...

* Alertmanager version:

	version=0.27.0

* Prometheus version:

	version=2.52.0-rc.1

* Alertmanager configuration file:

```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'discord_webhook'
receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'https://discordapp.com/api/webhooks/1247133913369940038/discordwebhooktoken'
```

* Prometheus configuration file:

```
global:
  scrape_interval: 15s                                                                          
  evaluation_interval: 15s                                                                  

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

```

*alert-rules.yml : 

```
groups:
- name: alerts
  rules:
  - alert: NodeExporterDown
    expr: up == 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "NodeExporter on {{ $labels.instance }} is down"
      description: "NodeExporter on {{ $labels.instance }} has been down for more than 5 seconds."
```

**Comment by davtoro** [comment]
@lazbord what was the issue?

**Comment by Mohamed-Mostafa69** [comment]
How did you made it works

**Comment by lazbord** [comment]
In Alertmanager config file, you have to group by alertname **AND** job, like so :

```
route:
  group_by: ['alertname','job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'discord_webhook'
receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'https://discordapp.com/api/webhooks/1247133913369940038/discordwebhooktoken'
```

**Comment by Mohamed-Mostafa69** [comment]
are you sure, bec. i did have the same config as you mentioned but didn't work for me
however the solution for me was running 1 more container for the discord integration
for more.

https://github.com/evanugarte/prometheus-monitoring-tutorial
https://github.com/benjojo/alertmanager-discord
```
discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: unless-stopped
    environment:
      DISCORD_WEBHOOK: <discord_hook>
    ports:
      - "9094:9094"
```

**Comment by lazbord** [comment]
Honestly, since the problem was resolved, I haven't touched a single config file. Good thing if your solution works!

**Comment by vnavalianyi** [comment]
> are you sure, bec. i did have the same config as you mentioned but didn't work for me however the solution for me was running 1 more container for the discord integration for more.
> 
> https://github.com/evanugarte/prometheus-monitoring-tutorial https://github.com/benjojo/alertmanager-discord
> 
> ```
> discord-alerts:
>     image: benjojo/alertmanager-discord
>     container_name: discord-alerts
>     restart: unless-stopped
>     environment:
>       DISCORD_WEBHOOK: <discord_hook>
>     ports:
>       - "9094:9094"
> ```

Hello, what was your original error in alertmanager?
I'm getting similar error as author:
caller=dispatch.go:353 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="discord-alerts/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 404: https://discord.com/api/webhooks/1231234124124/ewqr23r23: {\"message\": \"Unknown Webhook\", \"code\": 10015}

**Comment by clubitsupport** [comment]
in v0.28.0 still broken, message get set in [] embed description instead of content field

**Comment by gertcuykens** [comment]
In v0.28.0 still broken, message get set in [] embed description instead of content field

**Comment by aliakkas006** [comment]
how could you solve it?
