### ISSUE TITLE
silence db not compatible with newer versions?

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#782]
During a test upgrade with several silences configured, alertmanager chocked while I was modifying my silences.

> time="2017-05-04T12:38:52+02:00" level=error msg="api error: server_error: unexpected ID in new silence" source="api.go:604"

After this occured, all alertmanager gui pages didn't render properly. Is a full wipe recommended during upgrades?

**Comment by stuartnelson3** [comment]
That error occurs when you attempt to create a silence from json that has an ID field. In the current data model, silences are immutable, and can not be modified.

Silences from v0.5+ are forward compatible. If you do a rolling upgrade and the new instances have time to receive the silences via gossip from the old instances, it should be fine.

In the future, this sort of message should be directed to the prometheus-users mailing list, as it was a usage question vs. a bug report.

**Comment by fabxc** [comment]
From which version did you upgrade to which version?

**Comment by raypettersen** [comment]
I upgraded from 0.4.2. 

Why on earth has the silences gone into a non-modified state? If we want to extend a maintenance window, the workflow chokes. Same if we miss with the first silence (typo for instance). Also, I am not able to delete any silences. The button exists, but doesn't do anything. I'm confused, is the GUI being deprecated? We're really stuck at 0.4.2 here.

**Comment by fabxc** [comment]
Going from 0.4 the silences can indeed not be trivially ported due to disk format changes.

The immutability doesn't mean we want to prohibit any of the workflows you described. It is more about the underlying implementation. We want to be able to track a consistent history of what silences where active at which point in time.
This means if you change a matcher of an existing silence, it gets expired and a new one with the new matchers is created. Extending a window of an active silence is allowed as it doesn't mutate history. What we want to prohibit is being able to intentionally or accidentally modify what effect silences had on the past.

What do you mean by not being able to delete any silences? There should only be an "expire" button in 0.5 or higher.

**Comment by raypettersen** [comment]
Ok, we'll try to adapt to the new way of doing things but we'll really miss being able to update our silences.

Regarding what you're saying about the expire button, you're right. After viewing the GUI in incognito everything displays properly. There are some caching issues going from 0.4.2 to 5+ it seems.

**Comment by fabxc** [comment]
To be clear, from a UX perspective, you should still be able to update your silences. If it was a change mutating the past, it should just result in the silence being expired and being superseded by a new one.

The screenshot indicates an UI issue. We are very aware of the UI's shortcomings and @mxinden @stuartnelson3 and @w0rm are working hard on a more stable replacement, which should be able to launch soon.

**Comment by raypettersen** [comment]
Thanks for the feedback. I totally respect the time and effort you guys are putting into this. I just hope my input is valuable and not creating too much noise.

I found another UI issue. Silences created put in the future (start and expire), displays the delete button, and I am not able to expire the silence if I change my mind or if the silence is faulty. 

This thread is getting messy. Should I create two issues? One for what I just described, and one for the screenshot above?

**Comment by mxinden** [comment]
@raypettersen Caching issues should be fixed by #772 and will be merged into master with the new UI.

**Comment by raypettersen** [comment]
Perfect, thanks. 
Still don't think the future-silence delete-button is cache though. Seems to be a dead-lock.

**Comment by raypettersen** [comment]
I've split this thread into two issues. #784 #783
